#!/usr/bin/env bash
# run_local_backend.sh — launch CodeSeek backend for local development.
#
# By default this script PRESERVES the local SQLite database to keep
# GitHub authentication sessions and repository session states.
#
# To perform a clean start (wipe DB, session data, ingestion caches):
#   ./scripts/run_local_backend.sh --clean
#   OR
#   CODESEEK_CLEAN_START=1 ./scripts/run_local_backend.sh
set -euo pipefail

# Parse command line options
cli_clean=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)
      cli_clean=1
      shift
      ;;
    --help)
      echo "Usage: $0 [options]"
      echo ""
      echo "Options:"
      echo "  --clean    Force a clean start, wiping all local state (DB, session data, ingestion caches)."
      echo "  --help     Show this help message."
      echo ""
      echo "By default, this script preserves the local database to keep authentication sessions and repository session state."
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Use --help to see available options."
      exit 1
      ;;
  esac
done


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "$BACKEND_ROOT"

echo "[local-backend] preparing local backend"

# ---------------------------------------------------------------------------
# Load .env first so the variables below can be overridden per-project.
# ---------------------------------------------------------------------------
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# ---------------------------------------------------------------------------
# Runtime defaults (env takes precedence if already set).
# ---------------------------------------------------------------------------
export RETRIEVAL_REPO_ROOT="$BACKEND_ROOT"
export CODESEEK_TENANT_ID="${CODESEEK_TENANT_ID:-local}"
export CODESEEK_API_KEY="${CODESEEK_API_KEY:-local-dev-key}"

# Prefer SQLite for local dev unless caller forces Postgres.
if [[ "${CODESEEK_FORCE_POSTGRES:-0}" != "1" ]]; then
  export CODESEEK_DB_BACKEND="sqlite"
  unset CODESEEK_DATABASE_URL 2>/dev/null || true
fi

# Real paths used by the backend (must match db.py / session_indexer.py defaults).
CODESEEK_DB_PATH="${CODESEEK_DB_PATH:-/tmp/codeseek.sqlite3}"
export CODESEEK_DB_PATH

CODESEEK_REPO_WORKSPACE="${CODESEEK_REPO_WORKSPACE:-/tmp/codeseek_repo_workspace}"
export CODESEEK_REPO_WORKSPACE

INGESTION_TEMP_CLONE_DIR="${INGESTION_TEMP_CLONE_DIR:-/tmp/rag_ingestion}"
export INGESTION_TEMP_CLONE_DIR

# Ingestion / retrieval tuning for local dev.
export QDRANT_RECREATE_COLLECTION="${QDRANT_RECREATE_COLLECTION:-1}"
export INGESTION_ENABLE_INCREMENTAL_FILE_SKIP="${INGESTION_ENABLE_INCREMENTAL_FILE_SKIP:-0}"
export RETRIEVAL_ENABLE_DENSE="${RETRIEVAL_ENABLE_DENSE:-0}"
export RETRIEVAL_ENABLE_LEXICAL="${RETRIEVAL_ENABLE_LEXICAL:-1}"

# LLM chunk description settings.
export CHUNK_DESCRIPTION_MAX_CHUNKS="${CHUNK_DESCRIPTION_MAX_CHUNKS:-80}"
export CHUNK_DESCRIPTION_SLEEP_SECONDS="${CHUNK_DESCRIPTION_SLEEP_SECONDS:-0}"
export CHUNK_DESCRIPTION_RETRY_ON_RATE_LIMIT="${CHUNK_DESCRIPTION_RETRY_ON_RATE_LIMIT:-0}"
export CHUNK_DESCRIPTION_MAX_INPUT_CHARS="${CHUNK_DESCRIPTION_MAX_INPUT_CHARS:-1200}"
export CHUNK_DESCRIPTION_MAX_OUTPUT_TOKENS="${CHUNK_DESCRIPTION_MAX_OUTPUT_TOKENS:-60}"
export RETRIEVAL_LOCAL_LLM_TIMEOUT_SECONDS="${RETRIEVAL_LOCAL_LLM_TIMEOUT_SECONDS:-90}"

# ---------------------------------------------------------------------------
# Clean-start execution:
# Preserves local database by default. If --clean is passed or
# CODESEEK_CLEAN_START=1 is specified in the environment, wips the state.
# ---------------------------------------------------------------------------
CLEAN_START="${CODESEEK_CLEAN_START:-0}"
if [[ "$cli_clean" == "1" ]]; then
  CLEAN_START=1
fi
export CODESEEK_CLEAN_START="$CLEAN_START"

if [[ "$CLEAN_START" == "1" ]]; then
  echo "[local-backend] clean start requested"
  echo "[local-backend] ⚠  If the browser shows 401 after restart, log in again — auth state was reset."

  # --- SQLite database (all persistent session/auth/provider state) ---
  if [[ -f "$CODESEEK_DB_PATH" ]]; then
    echo "[local-backend] removing local db: $CODESEEK_DB_PATH"
    rm -f "$CODESEEK_DB_PATH"
  fi
  # SQLite WAL / shared-memory sidecars.
  rm -f "${CODESEEK_DB_PATH}-wal" "${CODESEEK_DB_PATH}-shm" 2>/dev/null || true
  echo "[local-backend] database will be recreated on startup"

  # --- Cloned repo workspace (sessions checked out by the indexer) ---
  if [[ -d "$CODESEEK_REPO_WORKSPACE" ]]; then
    echo "[local-backend] removing repo workspace: $CODESEEK_REPO_WORKSPACE"
    rm -rf "$CODESEEK_REPO_WORKSPACE"
  fi

  # --- Ingestion temp clones ---
  if [[ -d "$INGESTION_TEMP_CLONE_DIR" ]]; then
    echo "[local-backend] removing ingestion temp dir: $INGESTION_TEMP_CLONE_DIR"
    rm -rf "$INGESTION_TEMP_CLONE_DIR"
  fi

  # --- .rag_ingestion_state.json files generated by CodeSeek inside backend dir only ---
  # (does NOT touch user source repos outside BACKEND_ROOT)
  find "$BACKEND_ROOT" -maxdepth 6 -name ".rag_ingestion_state.json" -print -delete 2>/dev/null || true

  # --- Python caches (optional, speeds up a cold import check) ---
  find "$BACKEND_ROOT" -type d \( -name "__pycache__" -o -name ".pytest_cache" \) \
    -prune -exec rm -rf {} + 2>/dev/null || true

else
  if [[ -f "$CODESEEK_DB_PATH" ]]; then
    echo "[local-backend] preserving local db: $CODESEEK_DB_PATH"
  else
    echo "[local-backend] local db not found: $CODESEEK_DB_PATH (will be created on startup)"
  fi
fi

echo "[local-backend] starting backend (port 8000)"

exec ./.venv/bin/uvicorn retrieval.api_service:app --host 0.0.0.0 --port 8000
